### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by brntbeer** [brntbeer/practice-repository#1]
# Personal Information
- Name: Brent Beer
- Location: San Francisco, CA
- Favorite Restaurant: Chez Maman

cc: @jaw6 @PatrickBM @moby @meentastic for any feedback you may have about this information.

**Comment by meentastic** [comment]
i've always wanted to try chez maman!

**Comment by schaar** [comment]
:zap:

**Comment by brntbeer** [comment]
![](http://i.imgur.com/B0wld.gif)
